version: "3.9"

services:
  reverse-proxy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://binenso:strongpassword@db:5432/binenso_db?schema=public
      - JWT_SECRET=your_jwt_secret_key
      - JWT_REFRESH_SECRET=your_refresh_token_secret
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: binenso
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: binenso_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
